FROM node:20-alpine AS build
WORKDIR /app
COPY src/app/TDMS/front-end/package*.json ./
RUN npm install
COPY src/app/TDMS/front-end/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]